os:
  - linux

language: generic

env:
- PY=2.7
- PY=3.6
- PY=3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin

before_install:
- if [ "$PY" == "2.7" ];  then
    wget "https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh" -O miniconda.sh;
  else
    wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh;
  fi
- chmod +x miniconda.sh;
- ./miniconda.sh -b  -p /home/travis/miniconda;
- export PATH=/home/travis/miniconda/bin:$PATH;

install:
- conda install --yes python=$PY numpy scipy nose sphinx mock swig pip;
- pip install --upgrade pip;
- pip install mpi4py;

# install pyoptsparse
- git clone https://github.com/mdolab/pyoptsparse.git;
- cd pyoptsparse;
- python setup.py install;
- cd ..;

- pip install coverage;
- pip install coveralls;
- pip install testflo==1.3.6;
- export PATH=$HOME/.local/bin:$PATH;

# install openmdao and sphinx-travis
# we only install docs dependencies on py3
- git clone https://github.com/openmdao/openmdao.git;
- cd openmdao;
- if [ "$PY" == "3.7" ];  then
    pip install --user travis-sphinx;
    pip install ".[docs]";
  else
    pip install ".";
  fi
  
  - cd ..;

# install openaerostruct itself
- pip install -e .;

script:
- export PYTHONPATH=$PYTHONPATH:$PWD
- testflo -n 1 openaerostruct --coverage --coverpkg openaerostruct --cover-omit \*tests/\* --cover-omit \*docs/\*;
- if [ "$PY" == "3.7" ];  then
    travis-sphinx build --source=openaerostruct/docs;
  fi

after_success:
- if [ "$PY" == "3.7" ];  then
    travis-sphinx deploy;
    coveralls;
  fi
